### ISSUE TITLE
Crash when using countryFilter

### ISSUE THREAD

**Issue by Gintasz** [imtoori/CountryCodePicker#61]
I'm using country_code_picker 1.3.7, a crash occurs when I add the countryFilter parametes:

```
CountryCodePicker(
                  countryFilter: ["de", "lt"],
                  showCountryOnly: true,
                  flagWidth: 60,
                  showOnlyCountryWhenClosed: true,
                  initialSelection: "lt",
                  textStyle: TextStyle(fontSize: 0),
                )
```

```

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following RangeError was thrown building DottedBorder:
RangeError (index): Invalid value: Valid value range is empty: 0

The relevant error-causing widget was: 
  DottedBorder file:///Users/gintas/Documents/AppProjects/accounting/accounting/lib/maincontent/clients/editinvoice/EditInvoiceScreen.dart:261:18
When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:146:60)
#1      _CountryCodePickerState.initState.<anonymous closure> (package:country_code_picker/country_code_picker.dart:189:33)
#2      ListMixin.firstWhere (dart:collection/list.dart:149:38)
#3      _CountryCodePickerState.initState (package:country_code_picker/country_code_picker.dart:185:31)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 6 of 744 libraries in 1,525ms.
```

Without countryFilter parameter it doesn't crash. Crash occurs on widget is loaded, not when on tap is called.

```
gintas-mac:lifetrens gintas$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.16.4-pre.18, on Mac OS X 10.15.3 19D76, locale
    en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[!] VS Code (version 1.43.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (4 available)

! Doctor found issues in 1 category.
gintas-mac:lifetrens gintas$ 
```

**Comment by imtoori** [comment]
I just fixed it with the last version
